config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :employees do 
  	collection do
  		get 'all/(:company_param/(:role_param))', :action => :all
  		get 'employees_table/(:company_param/(:role_param))', :action => :employees_table
  	end	
  end

  resources :roles

  resources :companies

  resources :accounts

  #resources :persons

  root 'welcome#index'


  #jwt
  #post 'authenticate', to: 'authentication#authenticate'

  #get 'login', to: 'authentication#login'

  get   "login",       to: "sessions#new"
  post   "login",       to: "sessions#create"
  delete "logout",      to: "sessions#destroy"

  post "register",      to: "users#register"

  	#if you are under postman you should pass yor json like this 
  	#{
	#"user":{
	#	"name" : "test",
	#	"email" : "test@test.com",
	#	"password": "1234",
	#	"password_confirmation": "1234"
	#}
	#}

end

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :role, optional: true
	belongs_to :company, optional: true 
	validates :name, presence: true, length: {minimum: 2, maximum: 15}, format: { with: /\A[a-zA-Z _]*\Z/ }
	validates :lastname, presence: true, length: {minimum: 2, maximum: 15}, format: { with: /\A[a-zA-Z _]*\Z/ }
	validates :dni, presence: true, length: {minimum: 8, maximum: 15}, format: { with: /\A[0-9]*\Z/ }
	validates :birthday, presence: true
	#validates :role, presence: true
	scope :company_id, lambda {|company_id| where(:company_id => company_id)}
	scope :role_id, lambda {|role_id| where(:role_id => role_id)}
end

app/controllers/employees_controller.rb
class EmployeesController < ApiController
	before_action :require_token_authentication
	before_action :isSuperAdmin? || 
				  :isAdmin?, except: [:index, :show] || 
				  :isEditor?, except: [:index, :show, :update] ||
				  :isEmployee?, except: [:show] 
	#before_action :current_user
	def index
		@employees = Employee.all

		render json: {status: 200, employees: @employees} 
	end
	def new
		@employee = Employee.new
	end 
	def edit
		@employee = Employee.find(params[:id])
	end
	def create 
		@employee = Employee.new(employee_params)
		if @employee.save
			render json: {status: 200}
			#redirect_to @employee
		else
			render json: {status: 400, errors: @employee.errors}
			#render 'new'
		end
	end
	def update 
		@employee = Employee.find(params[:id])
		if @employee.update(employee_params) #you can use update_attributes also
			render json: {status: 200}
			#redirect_to @employee
		else
			render json: {status: 400, errors: @employee.errors}
			#render 'edit'
		end
	end
	def destroy 
		@employee = Employee.find(params[:id])
		@employee.destroy
		render json: {status: 200}
		#redirect_to employees_path
		#redirect_to request.referrer
	end 
	def show 
		@employee = Employee.find(params[:id])
		render json: {status: 200, employee: @employee} 
	end
	#----------------------------------CUSTOM------------------------------------#
	def all
		@employees = Employee.where(nil)
		@employees = @employees.company_id(params[:company_param]) if params[:company_param].present?
		@employees = @employees.role_id(params[:role_param]) if params[:role_param].present?
		#@employees = Employee.where("company_id = #{params[:company_param]}").where("role_id = #{params[:role_param]}")
		
		render template: "employees/all"
	end
	def employees_table
		@employees = Employee.where(nil)
		@employees = @employees.company_id(params[:company_param]) if params[:company_param].present?
		@employees = @employees.role_id(params[:role_param]) if params[:role_param].present?
		#@employees = Employee.where("company_id = #{params[:company_param]}").where("role_id = #{params[:role_param]}")
		
		#render template: "employees/employees_table"
		render json: {status: 200, employees: @employees} 
	end


	private
		def employee_params
			params.require(:employee).permit(:name, :lastname, :dni, :age, :birthday, :address, :company_id, :role_id)
		end 
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/views/employees/_form.html.erb
<%= form_for @employee do |form| %>
	<% if @employee.errors.any? %>
    	<div id="error_explanation">
      		<h2>
        		<%= pluralize(@employee.errors.count, "error") %> The registered employee cannot be saved:
      		</h2>
      		<ul>
        		<% @employee.errors.full_messages.each do |msg| %>
          			<li><%= msg %></li>
        		<% end %>
        		<!--
        		<%= messages = @employee.errors.details.keys.map { |attr|  content_tag(:li, @employee.errors.full_messages_for(attr).first)}.join %>
        		-->
      		</ul>
    	</div>
  	<% end %>
	<p>
		<%= form.label :name %><br>
		<%= form.text_field :name%>
	</p>
	<p>
		<%= form.label :lastname %><br>
		<%= form.text_field :lastname%>
	</p>
	<p>
		<%= form.label :dni %><br>
		<%= form.text_field :dni %>
	</p>
	<p>
		<%= form.label :age %><br>
		<%= form.number_field :age %>
	</p>
	<p>
		<%= form.label :birthday %><br>
		<%= form.date_field :birthday %>
	</p>
	<p>
		<%= form.label :address %><br>
		<%= form.text_field :address %>
	</p>
	<p>
		<%= form.label :company %><br />
  		<%= form.select :company_id, options_for_select(Company.all.map{|s|[s.name, s.id]}.insert(0, "")) %>
	</p>
	<p>
		<%= form.label :role %><br />
  		<%= form.select :role_id, options_for_select(Role.all.map{|s|[s.name, s.id]}.insert(0, "")) %>
	</p>
	<p>
		<%= form.submit %>
	</p>
<% end %>

<%= link_to 'Back', employees_path %>

app/views/employees/all.html.erb
<%= javascript_pack_tag 'application' %>

<h1>Listing employees</h1>
 
<!--
<%= select_tag('company', options_from_collection_for_select(Company.all, 'id', 'name'), prompt: "Select a Company", id: "company") %>
<%= select_tag('role', options_from_collection_for_select(Role.all, 'id', 'name'), prompt: "Select a Role", id: "role") %>
-->

<%= react_component("HelloWorld", { companies: Company.all, roles: Role.all, url: 'employees_table' }) %>
<br>
<%= link_to 'New Employee', new_employee_path %>

<p><%= link_to 'Main Page', root_path %></p>

<script type="text/javascript">
	var queryParameters = {}, queryString = location.search.substring(1), re = /([^&=]+)=([^&]*)/g, m;
	while (m = re.exec(queryString)) {
    	queryParameters[decodeURIComponent(m[1])] = decodeURIComponent(m[2]);
	}
	$( document ).ready(function() {
	   
	});

	var url = "/employees/employees_table?company_param=&role_param=";
	$("#company").on("change", function(){
		queryParameters['company'] = $(this).val();
		//location.search = $.param(queryParameters);
		arrayUrl = url.split("company_param=");
		subUrl = arrayUrl[1].split("&");
		if(subUrl.length == 2){
			url = arrayUrl[0] + "company_param=" + $(this).val() + "&" + subUrl[1];
		}else{
			url = arrayUrl[0] + "company_param=" + $(this).val();
		}
		$.ajax({url: url, success: function(data){
	        console.log(data);
	    }});	
	});
	$("#role").on("change", function(){
		queryParameters['role'] = $(this).val();
		//location.search = $.param(queryParameters);
		arrayUrl = url.split("role_param="); 
		subUrl = arrayUrl[1].split("&");
		if(subUrl.length == 2){
			url = arrayUrl[0] + "role_param=" + $(this).val() + "&" + subUrl[1];
		}else{
			url = arrayUrl[0] + "role_param=" + $(this).val();
		}
		list();
	});


	function list() {
		$.ajax({url: url, success: function(data){
	        employees = data.employees;
	        $('#employees_table tbody').html("");
	        console.log(data);
	        $.each(employees, function(i) {
	        	$('#employees_table tbody').append(
	        	 	"<tr>" +
	        	 		"<td>" + employees[i].name +"</td>" +
	        	 		"<td>" + employees[i].lastname +"</td>" +
	        	 		"<td><a href='/employees/" + employees[i].id + "'>Show</a></td>" +
	        	 		"<td><a href='/employees/" + employees[i].id + "/edit'>Edit</a></td>" + 
      					"<td><a id=\"employee-" + employees[i].id + "\" '>Delete</a></td>" +
	        	 	"</tr>"
	        	 );

	        	 $('#exployee' + employees[i].id).click( function(e) {
	        	 	e.preventDefault();

	        	 	$.ajax({
	        	 		method: 'delete',
	        	 		url: '/employees/' + employees[i].id,
	        	 		success: function(e) {
	        	 			console.log(e);
	        	 			list();
	        	 		},error: function(e){
	        	 			console.log('error', e);
	        	 		}
	        	 	})

	        	 })	
	        });
	    }});	
	}
</script>

app/views/employees/edit.html.erb
<h1> Edit Employee </h1>

<%= render 'form' %>

app/views/employees/employees_table.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Lastname</th>
  </tr>

 
  <% @employees.each do |employee| %>
    <tr>
      <td><%= employee.name %></td>
      <td><%= employee.lastname %></td>
      <td><%= link_to 'Show', employee_path(employee) %></td>
      <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
      <td><%= link_to 'Destroy', employee_path(employee), method: :delete,  data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/employees/index.html.erb
<h1>Listing employees</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Lastname</th>
  </tr>
 
  <% @employees.each do |employee| %>
    <tr>
      <td><%= employee.name %></td>
      <td><%= employee.lastname %></td>
      <td><%= link_to 'Show', employee_path(employee) %></td>
      <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
      <td><%= link_to 'Destroy', employee_path(employee), method: :delete,  data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'New Employee', new_employee_path %>

<p><%= link_to 'Main Page', root_path %></p>

<%= link_to('Logout', logout_path, method: :delete) %>

app/views/employees/new.html.erb
<h1> New Employee </h1>

<%= render 'form' %>

app/views/employees/show.html.erb
<h1>Employee Information</h1>
<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>
 
<p>
  <strong>Last Name:</strong>
  <%= @employee.lastname %>
</p>

<p>
  <strong>DNI:</strong>
  <%= @employee.dni %>
</p>

<p>
  <strong>Age:</strong>
  <%= @employee.age %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @employee.birthday %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>Company:</strong>
  <% if @employee.company.present?  %>
    <%= @employee.company.name %>
  <% end %>
</p>

<p>
  <strong>Role:</strong>
  <% if @employee.role.present?  %>
    <%= @employee.role.name %>
  <% end  %>
</p>

<%= link_to 'Listing Employees', employees_path %>