config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :employees do 
  	collection do
  		get 'all/(:company_param/(:role_param))', :action => :all
  		get 'employees_table/(:company_param/(:role_param))', :action => :employees_table
  	end	
  end

  resources :roles

  resources :companies

  resources :accounts

  #resources :persons

  root 'welcome#index'


  #jwt
  #post 'authenticate', to: 'authentication#authenticate'

  #get 'login', to: 'authentication#login'

  get   "login",       to: "sessions#new"
  post   "login",       to: "sessions#create"
  delete "logout",      to: "sessions#destroy"

  post "register",      to: "users#register"

  	#if you are under postman you should pass yor json like this 
  	#{
	#"user":{
	#	"name" : "test",
	#	"email" : "test@test.com",
	#	"password": "1234",
	#	"password_confirmation": "1234"
	#}
	#}

end

app/models/company.rb
class Company < ApplicationRecord
	has_many :employee, dependent: :restrict_with_error
	validates :name, presence: true, length: {minimum: 2, maximum: 20}, format: { with: /\A[a-zA-Z _]*\Z/ }
end

app/controllers/companies_controller.rb
class CompaniesController < ApiController
	before_action :require_token_authentication
	before_action :isSuperAdmin? || 
				  :isAdmin?, except: [:index, :show] || 
				  :isEditor?, except: [:index, :show, :update] ||
				  :isEmployee?, except: [] 
	def index
		@companies = Company.all
		render json: {status: 200, companies: @companies}
	end
	def new
		@company = Company.new
	end 
	def edit
		@company = Company.find(params[:id])
	end
	def create 
		@company = Company.new(company_params)
		if @company.save
			render json: {status: 200}
			#redirect_to @company
		else
			render json: {status: 400, errors: @company.errors}
			#render 'new'
		end
	end
	def update 
		@company = Company.find(params[:id])
		if @company.update(company_params) #you can use update_attributes also
			redirect_to @company
		else
			render 'edit'
		end
	end
	def destroy 
		@company = Company.find(params[:id])
		#unless @company.destroy
		#	flash[:error] ="The Company: #{@company.name} cannot be deleted because it's been referenced"
		#else
		#	flash[:error] = "The Company was succesfully deleted" 
		#end 
		
		render json: {status: 200}
		#redirect_to companies_path
	end 
	def show 
		@company = Company.find(params[:id]) 
		render json: {status: 200, company: @company} 
	end

	private
		def company_params
			params.require(:company).permit(:name, :work_area)
		end 
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |form| %>
	<% if @company.errors.any? %>
    	<div id="error_explanation">
      		<h2>
        		<%= pluralize(@company.errors.count, "error") %> The registered company cannot be saved:
      		</h2>
      		<ul>
        		<% @company.errors.full_messages.each do |msg| %>
          			<li><%= msg %></li>
        		<% end %>
      		</ul>
    	</div>
  	<% end %>
	<p>
		<%= form.label :name %><br>
		<%= form.text_field :name%>
	</p>
	<p>
		<%= form.label :work_area %><br>
		<%= form.text_field :work_area%>
	</p>
	<p>
		<%= form.submit %>
	</p>
<% end %>

<%= link_to 'Back', companies_path %>

app/views/companies/edit.html.erb
<h1>Edit Company</h1>

<%= render 'form' %>

app/views/companies/index.html.erb
<h1>Listing Companies</h1>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

<table>
  <tr>
    <th>Name</th>
    <th>Area</th>
  </tr>
 
  <% @companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= company.work_area %></td>
      <td><%= link_to 'Show', company_path(company) %></td>
      <td><%= link_to 'Edit', edit_company_path(company) %></td>
      <td><%= link_to 'Destroy', company_path(company), method: :delete,  data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'New Company', new_company_path %>

<p><%= link_to 'Main Page', root_path %></p>

app/views/companies/new.html.erb
<h1> New Company </h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<h1>Employee Information</h1>
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>
 
<p>
  <strong>Last Name:</strong>
  <%= @company.work_area %>
</p>

<%= link_to 'Listing Companies', companies_path %>