config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :employees do 
  	collection do
  		get 'all/(:company_param/(:role_param))', :action => :all
  		get 'employees_table/(:company_param/(:role_param))', :action => :employees_table
  	end	
  end

  resources :roles

  resources :companies

  resources :accounts

  #resources :persons

  root 'welcome#index'


  #jwt
  #post 'authenticate', to: 'authentication#authenticate'

  #get 'login', to: 'authentication#login'

  get   "login",       to: "sessions#new"
  post   "login",       to: "sessions#create"
  delete "logout",      to: "sessions#destroy"

  post "register",      to: "users#register"

  	#if you are under postman you should pass yor json like this 
  	#{
	#"user":{
	#	"name" : "test",
	#	"email" : "test@test.com",
	#	"password": "1234",
	#	"password_confirmation": "1234"
	#}
	#}

end

app/models/role.rb
class Role < ApplicationRecord
	has_many :employee, dependent: :restrict_with_error
	has_many :user
	validates :name, presence: true, length: {minimum: 2, maximum: 15}, format: { with: /\A[a-zA-Z _]*\Z/ }
end

app/controllers/roles_controller.rb
class RolesController < ApiController
	before_action :require_token_authentication
	before_action :isSuperAdmin? || 
				  :isAdmin?, except: [:index, :show] || 
				  :isEditor?, except: [:index, :show, :update] || 
				  :isEmployee?, except: []
	def index
		@roles = Role.all
		render json: {status: 200, roles: @roles} 
	end
	def new
		@role = Role.new
	end 
	def edit
		@role = Role.find(params[:id])
	end
	def create 
		@role = Role.new(role_params)
		if @role.save
			#redirect_to @role
			render json: {status: 200}
		else
			#render 'new'
			render json: {status: 400, errors: @role.errors}
		end
	end
	def update 
		@role = Role.find(params[:id])
		if @role.update(role_params) #you can use update_attributes also
			render json: {status: 200}
			#redirect_to @role
		else
			#render 'edit'
			render json: {status: 400, errors: @role.errors}
		end
	end
	def destroy 
		@role = Role.find(params[:id])
		#unless @role.destroy
		#	flash[:error] ="The Role: #{@role.name} cannot be deleted because it's been referenced"
		#else
		#	flash[:error] = "The Role was succesfully deleted" 
		#end 
		
		render json: {status: 200}
		#redirect_to roles_path
	end 
	def show 
		@role = Role.find(params[:id]) 
		render json: {status: 200, role: @role} 
	end

	private
		def role_params
			params.require(:role).permit(:name)
		end 
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for @role do |form| %>
	<% if @role.errors.any? %>
    	<div id="error_explanation">
      		<h2>
        		<%= pluralize(@role.errors.count, "error") %> The registered role cannot be saved:
      		</h2>
      		<ul>
        		<% @role.errors.full_messages.each do |msg| %>
          			<li><%= msg %></li>
        		<% end %>
      		</ul>
    	</div>
  	<% end %>
	<p>
		<%= form.label :name %><br>
		<%= form.text_field :name%>
	</p>
	<p>
		<%= form.submit %>
	</p>
<% end %>

<%= link_to 'Back', roles_path %>

app/views/roles/edit.html.erb
<h1> Edit Role </h1>

<%= render 'form' %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

<table>
  <tr>
    <th>Name</th>
  </tr>
 
  <% @roles.each do |role| %>
    <% if role.errors.any? %>
      <h1>Hello</h1>
    <% end%>
    <tr>
      <td><%= role.name %></td>
      <td><%= link_to 'Show', role_path(role) %></td>
      <td><%= link_to 'Edit', edit_role_path(role) %></td>
      <td><%= link_to 'Destroy', role_path(role), method: :delete,  data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'New Role', new_role_path %>

<p><%= link_to 'Main Page', root_path %></p>

app/views/roles/new.html.erb
<h1> New Role </h1>

<%= render 'form' %>

app/views/roles/show.html.erb
<h1>Role Information</h1>
<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<%= link_to 'Listing Roles', roles_path %>